name: Lint, Format, Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - "*"

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        working-directory: ./scripts

      - name: Lint
        run: npm run lint
        working-directory: ./scripts

      - name: Format
        run: |
          npm run check-formatting
          git diff --exit-code || (echo "Code is not formatted correctly. Please run 'npm run format' locally to fix formatting issues." && exit 1)
        working-directory: ./scripts

      - name: Build
        run: npm run build
        working-directory: ./scripts
