name: Lint, Format, Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - "*"

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: cd scripts && npm run lint

      - name: Format
        run: |
          cd scripts
          npm run check-formatting
          git diff --exit-code || (echo "Code is not formatted correctly. Please run 'npm run format' locally to fix formatting issues." && exit 1)

      - name: Build
        run: cd scripts && npm run build
